In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [6]:
df = pd.read_csv('house_data.csv')

X = df[['Area']]
y = df['Price']

In [7]:
model = linear_model.LinearRegression()
model.fit(X,y)

LinearRegression()

In [8]:
model.coef_

array([200.])

In [9]:
model.intercept_

-19999.999999999884

In [11]:
model.predict([[5000]])

/Users/harishk/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([980000.])

## Save models to a file using pickle

In [12]:
import pickle

In [13]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [14]:
pwd

'/Users/harishk/Documents/Projects/ML/ML1'

In [16]:

with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [17]:
mp.coef_

array([200.])

In [18]:
mp.intercept_

-19999.999999999884

In [19]:
mp.predict([[5000]])

/Users/harishk/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([980000.])

In [23]:
import joblib

In [25]:
joblib.dump(model,'model_joblib')

['model_joblib']

## Load Saved model

In [27]:
mj = joblib.load('model_joblib')

In [28]:
mj.coef_

array([200.])

In [29]:
mj.intercept_

-19999.999999999884

In [30]:
mj.predict([[5000]])

/Users/harishk/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([980000.])