In [1]:
new_list = [1,2,3]


In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr * 5


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [10]:
np.arange(1,19)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.ones((2,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [13]:
newarr = np.arange(0,11)

In [14]:
newarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
newarr[2:6]

array([2, 3, 4, 5])

In [17]:
bool_arr = newarr > 2


In [18]:
bool_arr


array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [19]:
newarr[bool_arr]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
newarr[newarr < 5]

array([0, 1, 2, 3, 4])

In [3]:
arr = np.arange(1,11)

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[1:3]

array([2, 3])

In [7]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr_2d[1,2]

6

In [20]:
arr_2d[2:,:]

array([[7, 8, 9]])

In [21]:
arr = np.arange(0,11)

In [22]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [23]:
bool_arr = arr >5

In [24]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [25]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [26]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [27]:
arr[arr>6]

array([ 7,  8,  9, 10])

In [29]:
new_arr = np.arange(50).reshape(5,10)

In [30]:
new_arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [33]:
new_arr[:3,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.random.rand(1)

array([0.44654743])